name: sosmesh
description: SOS Mesh Emergency App

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '^3.10.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  flutter_blue_plus: ^1.35.3
  permission_handler: ^11.3.1
  geolocator: ^13.0.2
  connectivity_plus: ^6.1.0
  google_maps_flutter: ^2.10.0
  sqflite: ^2.4.1
  path_provider: ^2.1.5
  http: ^1.2.2
  uuid: ^4.5.1
  battery_plus: ^7.0.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.12
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

  assets:
    - assets/